### ISSUE TITLE
アルゴリズム選定の方針

### ISSUE THREAD

**Issue by rmasutani** [shinonome-inc/lossless_challenge_ryo#1]

**Comment by rmasutani** [comment]
・基本的にドキュメントを提出するアルゴリズムは**２種類**

・今考えていること（独り言）
-

-  理想型は論文調査して何か新規性のある手法を実装したい
    - しかしおそらく実装する時間はそれほどない（エラー直してPDCA回してを考えると）
    - 加えて新入生メンバーの負担を考えると複雑すぎる手法を実装して失敗するのもよくない

- 上記を踏まえると、シンプルな手法 or 既存の強力な手法を一つと何か面白いものを一つ提案するのが現実的な気がする
    - 既存だとpng, jpeg-lsあたりが強そう（難易度高め）

- 既存の手法のメリット
    - リファレンス、参考実装がいくらでもある
    - テストしやすい

- 独自手法に関するメモ
    - fashion-mnistは割と特徴的な画像群なのでその統計的特徴を利用したい
    - どうせ実装するなら何かストレングスが欲しい（高速、低メモリなど）

**Comment by rmasutani** [comment]
もう少し詳しく見てみたけどPNGはdeflateとヘッダの書き方理解すればいけそう
なんなら実装３日ぐらいしかかかんないんじゃないか？

**Comment by rmasutani** [comment]
pngをmnistみたいな画像に対して最適化することは出来るんだろうか

**Comment by rmasutani** [comment]
JPEG-LSを調べてみて思ったこと

予測輝度値を算出するところで機械学習を使う余地はありそう。実際何個か使ってる論文を見つけた。一般化ガウスを仮定してDPとかを使って最適化してるやつがおもしろそう

**Comment by hiroki-kojima** [comment]
@rmasutani 
論文タイトルおせーて

> 一般化ガウスを仮定してDPとかを使って最適化してるやつが

**Comment by rmasutani** [comment]
@hiroki-kojima https://www.jstage.jst.go.jp/article/itetr/26.76/0/26.76_19/_pdf

**Comment by hiroki-kojima** [comment]
@rmasutani サンクス．

弊研究室の手法です．これの類似手法で最も圧縮率の良いものにMRPがあります．
Cでコードも公開されているのでもし良ければ参考にしてみてください．

https://www.rs.tus.ac.jp/matsuda-lab/matsuda/mrp/index.html

**Comment by rmasutani** [comment]
@hiroki-kojima まじですか、、、理科大だったんでまさかとは思ってたんですが笑
コードあるのとても助かります、参考にします
