### ISSUE TITLE
提案

### ISSUE THREAD

**Issue by rmasutani** [shinonome-inc/lossless_challenge_ryo#2]
@piffett @ichinose0427 1つ目のオプションはPNGの実装でどうでしょうか？

概要としては、

- フィルターをかける
- deflate(LZSS+ハフマン)で圧縮
- ファイル出力

という感じです。さらに、以下に最適化として取り組みたいことをいくつか挙げると

- フィルターは行ごとに最適なものが変わるらしい → 探索してベストなものを決めたい(今回計算時間は判断基準ではないので)
- deflateの最適化→ハフマン木の容量を減少させられるか？

大体こんな感じになります。もし良ければ自分でも調べてみて下さい

**Comment by rmasutani** [comment]
28行分のフィルター情報をどう書き込むか問題はある気がしないでもない

→フィルターの種類は標準だと5らしい。ということはヘッダだけで40byteぐらい使う計算になる

**Comment by rmasutani** [comment]
ちなみに、独断と偏見ですが

- 理論的難易度：中
- 実装の難易度：中
- 実装の量：小

ぐらいなので非常にオススメな気がします。ただおそらく他の班はもっと難しいことをやってくるので勝ちたければこれより難しいことをやるしかない。（もしくは彼らも同じ手法を検討している可能性）

**Comment by rmasutani** [comment]
２つ目の案：

ひろきさんとかゆうじくんがtimesで言っていたやつ。ラベルごとに共通の辞書を作っておいてヘッダーの情報からいろいろ頑張る方法。多分ゆうじくんチームがやるのでボツだけど一応。（並列処理に取り組めば「同じ」手法にはならない説？）

**Comment by rmasutani** [comment]
３つ目の案：

これもひろきさんのアイデア丸パクリ。P(画像) = Σ P(画像|カテゴリ)P(カテゴリ)として上位のクラスの確率をヘッダーに追加。

※追加
正確にいうと、圧縮は

各ラベルに対応した辞書を作成
作っておいた学習モデルで与えられた画像のクラスを推定(上位数クラス)
圧縮してクラスをヘッダーに追加

の流れになるはず(要確認)(正直言ってスピード制限がないならこれはやる必要ないんじゃないかと思いつつも機械学習の良い勉強にはなる)

**Comment by rmasutani** [comment]
４つ目の案：JPEG-LS

https://ja.wikipedia.org/wiki/Lossless_JPEG これをみてもらった方が早いです

**Comment by piffett** [comment]
提案です

## 想定されるフロー

- 画像を読み込む
- どのMAPを用いるか決める
- 画像をMAPで展開
- エンコーダでエンコード
- MAP番号とエンコードされた情報をくっつける

- 圧縮されたデータから、MAP番号を取り出す
- 残ったデータをデコーダにかける
- MAP番号から該当MAPをとりだし、画像にする

## エンコーダを叩く時

```
python3 encode.py TMW/camera.pgm encoded default
↑最後の引数でエンコーダのバージョンを指定する
```

## デコーダを叩く時
```
python3 dedcode.py encoded decoded.png default
こちらも同様に最後にエンコーダのバージョンを指定する
```


## MAPについて

画像の特徴を捉えて圧縮率を向上させる方法として、MAPを作成することを考えた。チームとして活用するかはまだ検討中であるが、個人で運用してみて使用感がよければチーム開発に移植する

![MAP](https://user-images.githubusercontent.com/30842360/86226717-04b3ce00-bbc7-11ea-80cd-a2fe22ed6bf0.png)

**Comment by rmasutani** [comment]
共通辞書に関する独り言

どの単位で画像を分類するか問題

- 安直なのはラベルで分類
- もしくは教師なし学習で特徴を抽出(クラス数については自分らで設定) 

ラベルで分ける場合については作るのはイージーだけれども圧縮率がそこまで高まらない可能性あり

というかそもそも辞書の推定をどうやるんだろうか…
