### ISSUE TITLE
[PNG] フィルターの実装

### ISSUE THREAD

**Issue by rmasutani** [shinonome-inc/lossless_challenge_ryo#5]
fashion-mnistから画像を読み込んでフィルターを適用する関数を作成する。フィルタの種類はSubとUp　http://uno036.starfree.jp/PRGmanual/ImageFormatPng2/PNG-Filters.html
の２種類とする。

仕様はとりあえず以下

Parameters:
    img: np.ndarray
           入力画像

Returns:
    out: np.ndarray
          フィルター適用後の画像

**Comment by rmasutani** [comment]
ブランチ切るの忘れずに！

**Comment by ichinose0427** [comment]
> fashion-mnistから画像を読み込んでフィルターを適用する関数を作成する。フィルタの種類はSubとUp　http://uno036.starfree.jp/PRGmanual/ImageFormatPng2/PNG-Filters.html
> の２種類とする。
> 
> 仕様はとりあえず以下
> 
> Parameters:
> img: np.ndarray
> 入力画像
> 
> Returns:
> out: np.ndarray
> フィルター適用後の画像

**Comment by rmasutani** [comment]
@ichinose0427 一つ訂正。画像を読み込むパートはすでにencodeがやってくれてるのでやらなくていいです。

**Comment by rmasutani** [comment]
@ichinose0427 時間があるときにAverageとPaethも追加してみましょう

**Comment by rmasutani** [comment]
作った関数はfilter.pyにまとめてください
